language: python

cache: 
  pip: True

sudo: false

jobs:
    include:
    - name: test
      stage: test
      script:
        - ./ci-test.sh
      python:
        - "3.6"
        - "3.9"

after_success:
    - ./ci-cov.sh

branches:
    only:
    - master
    - /^v/

services:
    - mysql
